version: 2.1

orbs:
  slack: circleci/clack@3.4.2

jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "hello world"
      - slack/notify:
          channel: circleci
          color: '#42e2f4'
          message: Build executed.
